### PR TITLE
Upgrade python to 3.6

### PR DESCRIPTION
**Pull request by maaktweluit**
closes golemfactory/golem#2012

Switched the default python 3 to the latest python3.6

### CODE REVIEW

**Comment by tworec** [comment]
LGTM

**Comment by tworec** [comment]
closes golemfactory/golem#2012

**Review by ktomala — APPROVED** [review]
LGTM

**Comment by ktomala** [comment]
@maaktweluit Should we merge this?

**Comment by tworec** [comment]
yeah! go for it

**Comment by maaktweluit** [comment]
Sounds great! will release it today EOD to be ready for release next week

**Pull request merged**
